name: Bubble sort

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 13.3
      uses: actions/setup-python@v13.3
      with:
        python-version: "13.3"
    - name: Install pytest
      run: pip install pytest
    - name: Test with pytest
      run: pytest
